/**
 * Contact Types and Interfaces
 * Defines the shape and validation rules for contact data
 */

/**
 * Full Contact object - what comes from database
 * All fields are required and have specific formats
 */

// created these custom types for our ease and to ensure consistency, we use these types as
// parameters or return types of functions instead of writing manually for each function
// and there might become risk of inconsistency

export interface Contact {
  id: string; // Unique identifier (numeric string: "1", "2", etc.)
  name: string; // Full name (required, non-empty)
  email: string; // Email address (must be valid email format)
  phone: string; // Phone number (MUST be exactly 8 chars: "555-0001")
  address: string; // Full address (required, non-empty)
  createdAt: string; // ISO 8601 timestamp (e.g., "2025-01-01T08:00:00Z")
}

/**
 * Input for creating a new contact
 * Does NOT include id (generated by system) or createdAt (set to now)
 * Used for both API validation and form submission
 */
export interface CreateContactInput {
  name: string; // Required: 2-100 characters
  email: string; // Required: valid email format
  phone: string; // Required: exactly "555-XXXX" format (8 chars total)
  address: string; // Required: 5-200 characters
}

/**
 * Input for updating a contact
 * All fields are OPTIONAL - user can update just one field
 * Used for PATCH/PUT requests
 */
export interface UpdateContactInput {
  name?: string; // Optional: 2-100 characters if provided
  email?: string; // Optional: valid email format if provided
  phone?: string; // Optional: exactly "555-XXXX" format if provided
  address?: string; // Optional: 5-200 characters if provided
}

/**
 * API Response wrapper for single contact
 */
export interface ContactResponse {
  success: boolean;
  data?: Contact;
  error?: string;
}

/**
 * API Response wrapper for list of contacts
 */
export interface ContactListResponse {
  success: boolean;
  data?: Contact[];
  total?: number;
  error?: string;
}

/**
 * Validation result - either success or array of errors
 */
export interface ValidationResult {
  isValid: boolean;
  errors: ValidationError[];
}

/**
 * Validation error details
 */
export interface ValidationError {
  field: string; // Which field failed validation
  message: string; // What's wrong with it
}
